### ISSUE TITLE
xclipd doesn't capture event when copy-pasting between GUI VNC session and local MAC machine

### ISSUE THREAD

**Issue by coda-nsit** [jhunt/xclipd#1]
I open a TigerVNC GUI session. Then open a text file using gedit in the remote machine. The remote machine is a Fedora Linux. Then I run xclipd in the remote machine. Now when I copy-paste withing the remote machine all is good. But when I try to copy-paste something from the gedit to my local MAC, xclipd doesn't seem to detect this action. I know this because I have put several debug print statements in the xclipd.c file.

**Comment by jhunt** [comment]
There’s a lot to unpack here.

Are you connecting to TigerVNC to a Linux machine running X11, from your mac?  Where is xclipd running?
