### ISSUE TITLE
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"

### ISSUE THREAD

**Issue by Eleno4kaLap** [jhunt/xclipd#3]
Hello! I install xclipd in own docker container and when run my code I get error
`XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 14 requests (13 known processed) with 0 events remaining.`
      
Please tell me how you can solve this problem?

**Comment by jhunt** [comment]
My guess is that your docker container doesn't have visiblity to the sockets (TCP or UNIX domain) needed to communicate with the X server.  You'll need to bind-mount those in (for domain sockets) or ensure that addressing of the TCP endpoint is correct.
