### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by samhh** [jhunt/xclipd#4]
Have you considered versioning this software?

FYI I've made an [AUR package](https://aur.archlinux.org/packages/xclipd-git/) for it. Thanks for bringing sanity to my clipboard! :slightly_smiling_face:

**Comment by jhunt** [comment]
That sounds like a splendid idea.  I'm glad you found joy in the code!

**Comment by jhunt** [comment]
Hooray for 1.0.0!

https://github.com/jhunt/xclipd/releases/tag/v1.0.0
